version = 0.1
[default.deploy.parameters]
stack_name = "aichatcore-webapp"
resolve_s3 = true
s3_prefix = "aichatcore-webapp"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GithubRepository=\"https://github.com/suresha97/aichatcore\" GithubToken=\"{{resolve:secretsmanager:github-token:SecretString:github-token}}\" CognitoUserPoolName=\"aichatcore-api-userpool\" CognitoWebClientName=\"aichatcore-api-webclient\" ApiStackName=\"aichatcore-api\""
image_repositories = []
