repos:
  - hooks:
      - id: check-yaml
        args:
          - --unsafe
      - id: check-toml
      - id: check-json
      - args:
          - --autofix
          - --no-sort-keys
        id: pretty-format-json
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: check-added-large-files
        args:
          - --maxkb=600
      - id: mixed-line-ending
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.1
    hooks:
      - id: ruff
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 23.10.0
  - hooks:
      - args:
          - --show-error-codes
          - --ignore-missing-imports
          - --install-types
          - --non-interactive
          - --config-file
          - pyproject.toml
        id: mypy
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
#  - hooks:
#      - id: commitizen
#        stages:
#          - commit-msg
#    repo: https://github.com/commitizen-tools/commitizen
#    rev: 3.12.0
