version = 0.1
[default.deploy.parameters]
stack_name = "aichatcore-api"
resolve_s3 = true
s3_prefix = "aichatcore-api"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PineconeAPIKey=\"{{resolve:secretsmanager:aichatcore/pinecone_api_key:SecretString:aichatcore.pinecone_api_key}}\" OpenaiAPIKey=\"{{resolve:secretsmanager:aichatcore/openai_api_key:SecretString:aichatcore.openai_api_key}}\""
image_repositories = []
