version = 0.1
[default.deploy.parameters]
stack_name = "chatytt-api"
resolve_s3 = true
s3_prefix = "chatytt-api"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PineconeAPIKey=\"{{resolve:secretsmanager:pinecone-api-key:SecretString:pinecone-api-key}}\" OpenaiAPIKey=\"{{resolve:secretsmanager:openai-api-key:SecretString:openai-api-key}}\""
image_repositories = []
